//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by SlSvcUtil, version 3.7.0.0
// 
namespace NotQuiteAzure
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/NotQuiteAzure")]
    public partial class Customer : object
    {
        
        private NotQuiteAzure.Policy[] PoliciesField;
        
        private string addressField;
        
        private System.DateTime dateOfBirthField;
        
        private string emailField;
        
        private string firstNameField;
        
        private string homePhoneField;
        
        private string idField;
        
        private string lastNameField;
        
        private string workPhoneField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public NotQuiteAzure.Policy[] Policies
        {
            get
            {
                return this.PoliciesField;
            }
            set
            {
                this.PoliciesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dateOfBirth
        {
            get
            {
                return this.dateOfBirthField;
            }
            set
            {
                this.dateOfBirthField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string homePhone
        {
            get
            {
                return this.homePhoneField;
            }
            set
            {
                this.homePhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string workPhone
        {
            get
            {
                return this.workPhoneField;
            }
            set
            {
                this.workPhoneField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Policy", Namespace="http://schemas.datacontract.org/2004/07/NotQuiteAzure")]
    public partial class Policy : object
    {
        
        private string idField;
        
        private string makeField;
        
        private string modelField;
        
        private string registrationField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string make
        {
            get
            {
                return this.makeField;
            }
            set
            {
                this.makeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string model
        {
            get
            {
                return this.modelField;
            }
            set
            {
                this.modelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string registration
        {
            get
            {
                return this.registrationField;
            }
            set
            {
                this.registrationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Claim", Namespace="http://schemas.datacontract.org/2004/07/NotQuiteAzure")]
    public partial class Claim : object
    {
        
        private string customerIdField;
        
        private string idField;
        
        private string policyIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string customerId
        {
            get
            {
                return this.customerIdField;
            }
            set
            {
                this.customerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string policyId
        {
            get
            {
                return this.policyIdField;
            }
            set
            {
                this.policyIdField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="INotQuiteAzure")]
public interface INotQuiteAzure
{
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/INotQuiteAzure/Register", ReplyAction="http://tempuri.org/INotQuiteAzure/RegisterResponse")]
    System.IAsyncResult BeginRegister(string id, System.AsyncCallback callback, object asyncState);
    
    NotQuiteAzure.Customer EndRegister(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/INotQuiteAzure/CustomerCallRequest", ReplyAction="http://tempuri.org/INotQuiteAzure/CustomerCallRequestResponse")]
    System.IAsyncResult BeginCustomerCallRequest(string id, string customerPhone, System.AsyncCallback callback, object asyncState);
    
    bool EndCustomerCallRequest(System.IAsyncResult result);
    
    [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/INotQuiteAzure/RecordClaim", ReplyAction="http://tempuri.org/INotQuiteAzure/RecordClaimResponse")]
    System.IAsyncResult BeginRecordClaim(NotQuiteAzure.Claim claim, System.AsyncCallback callback, object asyncState);
    
    bool EndRecordClaim(System.IAsyncResult result);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface INotQuiteAzureChannel : INotQuiteAzure, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RegisterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public RegisterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public NotQuiteAzure.Customer Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((NotQuiteAzure.Customer)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CustomerCallRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public CustomerCallRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public bool Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class RecordClaimCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{
    
    private object[] results;
    
    public RecordClaimCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState)
    {
        this.results = results;
    }
    
    public bool Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((bool)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class NotQuiteAzureClient : System.ServiceModel.ClientBase<INotQuiteAzure>, INotQuiteAzure
{
    
    private BeginOperationDelegate onBeginRegisterDelegate;
    
    private EndOperationDelegate onEndRegisterDelegate;
    
    private System.Threading.SendOrPostCallback onRegisterCompletedDelegate;
    
    private BeginOperationDelegate onBeginCustomerCallRequestDelegate;
    
    private EndOperationDelegate onEndCustomerCallRequestDelegate;
    
    private System.Threading.SendOrPostCallback onCustomerCallRequestCompletedDelegate;
    
    private BeginOperationDelegate onBeginRecordClaimDelegate;
    
    private EndOperationDelegate onEndRecordClaimDelegate;
    
    private System.Threading.SendOrPostCallback onRecordClaimCompletedDelegate;
    
    private BeginOperationDelegate onBeginOpenDelegate;
    
    private EndOperationDelegate onEndOpenDelegate;
    
    private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
    
    private BeginOperationDelegate onBeginCloseDelegate;
    
    private EndOperationDelegate onEndCloseDelegate;
    
    private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
    
    public NotQuiteAzureClient()
    {
    }
    
    public NotQuiteAzureClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public NotQuiteAzureClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public NotQuiteAzureClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public NotQuiteAzureClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public System.Net.CookieContainer CookieContainer
    {
        get
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                return httpCookieContainerManager.CookieContainer;
            }
            else
            {
                return null;
            }
        }
        set
        {
            System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
            if ((httpCookieContainerManager != null))
            {
                httpCookieContainerManager.CookieContainer = value;
            }
            else
            {
                throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                        "ookieContainerBindingElement.");
            }
        }
    }
    
    public event System.EventHandler<RegisterCompletedEventArgs> RegisterCompleted;
    
    public event System.EventHandler<CustomerCallRequestCompletedEventArgs> CustomerCallRequestCompleted;
    
    public event System.EventHandler<RecordClaimCompletedEventArgs> RecordClaimCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
    
    public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult INotQuiteAzure.BeginRegister(string id, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginRegister(id, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    NotQuiteAzure.Customer INotQuiteAzure.EndRegister(System.IAsyncResult result)
    {
        return base.Channel.EndRegister(result);
    }
    
    private System.IAsyncResult OnBeginRegister(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string id = ((string)(inValues[0]));
        return ((INotQuiteAzure)(this)).BeginRegister(id, callback, asyncState);
    }
    
    private object[] OnEndRegister(System.IAsyncResult result)
    {
        NotQuiteAzure.Customer retVal = ((INotQuiteAzure)(this)).EndRegister(result);
        return new object[] {
                retVal};
    }
    
    private void OnRegisterCompleted(object state)
    {
        if ((this.RegisterCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.RegisterCompleted(this, new RegisterCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void RegisterAsync(string id)
    {
        this.RegisterAsync(id, null);
    }
    
    public void RegisterAsync(string id, object userState)
    {
        if ((this.onBeginRegisterDelegate == null))
        {
            this.onBeginRegisterDelegate = new BeginOperationDelegate(this.OnBeginRegister);
        }
        if ((this.onEndRegisterDelegate == null))
        {
            this.onEndRegisterDelegate = new EndOperationDelegate(this.OnEndRegister);
        }
        if ((this.onRegisterCompletedDelegate == null))
        {
            this.onRegisterCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRegisterCompleted);
        }
        base.InvokeAsync(this.onBeginRegisterDelegate, new object[] {
                    id}, this.onEndRegisterDelegate, this.onRegisterCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult INotQuiteAzure.BeginCustomerCallRequest(string id, string customerPhone, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginCustomerCallRequest(id, customerPhone, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    bool INotQuiteAzure.EndCustomerCallRequest(System.IAsyncResult result)
    {
        return base.Channel.EndCustomerCallRequest(result);
    }
    
    private System.IAsyncResult OnBeginCustomerCallRequest(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string id = ((string)(inValues[0]));
        string customerPhone = ((string)(inValues[1]));
        return ((INotQuiteAzure)(this)).BeginCustomerCallRequest(id, customerPhone, callback, asyncState);
    }
    
    private object[] OnEndCustomerCallRequest(System.IAsyncResult result)
    {
        bool retVal = ((INotQuiteAzure)(this)).EndCustomerCallRequest(result);
        return new object[] {
                retVal};
    }
    
    private void OnCustomerCallRequestCompleted(object state)
    {
        if ((this.CustomerCallRequestCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.CustomerCallRequestCompleted(this, new CustomerCallRequestCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void CustomerCallRequestAsync(string id, string customerPhone)
    {
        this.CustomerCallRequestAsync(id, customerPhone, null);
    }
    
    public void CustomerCallRequestAsync(string id, string customerPhone, object userState)
    {
        if ((this.onBeginCustomerCallRequestDelegate == null))
        {
            this.onBeginCustomerCallRequestDelegate = new BeginOperationDelegate(this.OnBeginCustomerCallRequest);
        }
        if ((this.onEndCustomerCallRequestDelegate == null))
        {
            this.onEndCustomerCallRequestDelegate = new EndOperationDelegate(this.OnEndCustomerCallRequest);
        }
        if ((this.onCustomerCallRequestCompletedDelegate == null))
        {
            this.onCustomerCallRequestCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCustomerCallRequestCompleted);
        }
        base.InvokeAsync(this.onBeginCustomerCallRequestDelegate, new object[] {
                    id,
                    customerPhone}, this.onEndCustomerCallRequestDelegate, this.onCustomerCallRequestCompletedDelegate, userState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult INotQuiteAzure.BeginRecordClaim(NotQuiteAzure.Claim claim, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginRecordClaim(claim, callback, asyncState);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    bool INotQuiteAzure.EndRecordClaim(System.IAsyncResult result)
    {
        return base.Channel.EndRecordClaim(result);
    }
    
    private System.IAsyncResult OnBeginRecordClaim(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        NotQuiteAzure.Claim claim = ((NotQuiteAzure.Claim)(inValues[0]));
        return ((INotQuiteAzure)(this)).BeginRecordClaim(claim, callback, asyncState);
    }
    
    private object[] OnEndRecordClaim(System.IAsyncResult result)
    {
        bool retVal = ((INotQuiteAzure)(this)).EndRecordClaim(result);
        return new object[] {
                retVal};
    }
    
    private void OnRecordClaimCompleted(object state)
    {
        if ((this.RecordClaimCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.RecordClaimCompleted(this, new RecordClaimCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void RecordClaimAsync(NotQuiteAzure.Claim claim)
    {
        this.RecordClaimAsync(claim, null);
    }
    
    public void RecordClaimAsync(NotQuiteAzure.Claim claim, object userState)
    {
        if ((this.onBeginRecordClaimDelegate == null))
        {
            this.onBeginRecordClaimDelegate = new BeginOperationDelegate(this.OnBeginRecordClaim);
        }
        if ((this.onEndRecordClaimDelegate == null))
        {
            this.onEndRecordClaimDelegate = new EndOperationDelegate(this.OnEndRecordClaim);
        }
        if ((this.onRecordClaimCompletedDelegate == null))
        {
            this.onRecordClaimCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRecordClaimCompleted);
        }
        base.InvokeAsync(this.onBeginRecordClaimDelegate, new object[] {
                    claim}, this.onEndRecordClaimDelegate, this.onRecordClaimCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
    }
    
    private object[] OnEndOpen(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
        return null;
    }
    
    private void OnOpenCompleted(object state)
    {
        if ((this.OpenCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void OpenAsync()
    {
        this.OpenAsync(null);
    }
    
    public void OpenAsync(object userState)
    {
        if ((this.onBeginOpenDelegate == null))
        {
            this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
        }
        if ((this.onEndOpenDelegate == null))
        {
            this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
        }
        if ((this.onOpenCompletedDelegate == null))
        {
            this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
        }
        base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
    }
    
    private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
    }
    
    private object[] OnEndClose(System.IAsyncResult result)
    {
        ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
        return null;
    }
    
    private void OnCloseCompleted(object state)
    {
        if ((this.CloseCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
        }
    }
    
    public void CloseAsync()
    {
        this.CloseAsync(null);
    }
    
    public void CloseAsync(object userState)
    {
        if ((this.onBeginCloseDelegate == null))
        {
            this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
        }
        if ((this.onEndCloseDelegate == null))
        {
            this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
        }
        if ((this.onCloseCompletedDelegate == null))
        {
            this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
        }
        base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
    }
    
    protected override INotQuiteAzure CreateChannel()
    {
        return new NotQuiteAzureClientChannel(this);
    }
    
    private class NotQuiteAzureClientChannel : ChannelBase<INotQuiteAzure>, INotQuiteAzure
    {
        
        public NotQuiteAzureClientChannel(System.ServiceModel.ClientBase<INotQuiteAzure> client) : 
                base(client)
        {
        }
        
        public System.IAsyncResult BeginRegister(string id, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = id;
            System.IAsyncResult _result = base.BeginInvoke("Register", _args, callback, asyncState);
            return _result;
        }
        
        public NotQuiteAzure.Customer EndRegister(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            NotQuiteAzure.Customer _result = ((NotQuiteAzure.Customer)(base.EndInvoke("Register", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginCustomerCallRequest(string id, string customerPhone, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[2];
            _args[0] = id;
            _args[1] = customerPhone;
            System.IAsyncResult _result = base.BeginInvoke("CustomerCallRequest", _args, callback, asyncState);
            return _result;
        }
        
        public bool EndCustomerCallRequest(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            bool _result = ((bool)(base.EndInvoke("CustomerCallRequest", _args, result)));
            return _result;
        }
        
        public System.IAsyncResult BeginRecordClaim(NotQuiteAzure.Claim claim, System.AsyncCallback callback, object asyncState)
        {
            object[] _args = new object[1];
            _args[0] = claim;
            System.IAsyncResult _result = base.BeginInvoke("RecordClaim", _args, callback, asyncState);
            return _result;
        }
        
        public bool EndRecordClaim(System.IAsyncResult result)
        {
            object[] _args = new object[0];
            bool _result = ((bool)(base.EndInvoke("RecordClaim", _args, result)));
            return _result;
        }
    }
}
